version: '3.4'

services:
  fluxodiario.api:
    image: ${DOCKER_REGISTRY-}fluxodiarioapi
    build:
      context: .
      dockerfile: FluxoDiario.Api/Dockerfile
    depends_on:
      - db
    ports:
      - 10000:80
      - 10001:443
    environment:
      - ConnectionStrings__Projeto=Server=db;Database=fluxoCaixaDb;User Id=sa;Password=Admin@123;TrustServerCertificate=true;
      - ASPNETCORE_ENVIRONMENT=Production
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=Admin@123
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql/data
    user: root    
volumes:
  sqlserver_data: